### ISSUE TITLE
Чем пользуюсь

### ISSUE THREAD

**Issue by agsochi** [Pshatsillo/OpenhabYandexAlice#1]
Открыть-закрыть шторы (dimmer)
Включить-выключить свет как по имени светильника так и в комнатах (switch, group)
Телевизор погромче (dimmer)
Включи РБК, включает телек и набирает 101

**Comment by Pshatsillo** [comment]
Спасибо!

вт, 14 февр. 2023 г., 12:27 agsochi ***@***.***>:

**Comment by MolRoman** [comment]
Из навыков:
- управление теплым полом (вкл/выкл, задание уставки по температуре, узнать текущую температуру)
- узнать температуру/влажность/CO2 в комнате
- управление светом

**Comment by Pshatsillo** [comment]
Спасибо!
