### ISSUE TITLE
Min и max для range

### ISSUE THREAD

**Issue by Ilia-SB** [Pshatsillo/OpenhabYandexAlice#2]
Настроил несколько термостатов, кондиционеров и датчиков. Все работает. Спасибо за биндинг!
Подскажите, есть ли возможность настроить значения min и max для item с тегом range? Например, для установки температуры кондиционера.

**Comment by Pshatsillo** [comment]
По-идее и с range должно работать. Если нет - посмотрю

ср, 12 июл. 2023 г., 23:27 Ilia-SB ***@***.***>:

**Comment by Ilia-SB** [comment]
Вот мой item:
`
Number AC_Target_Temp_1 "Set temp" <temperature> (gAlice_AC_1) ["Setpoint","Temperature","range"] {channel=...}
`
В приложении Яндекс могу установить температуру от 0 до 100. Из wiki не понял, как можно прописать ограничения.

**Comment by Pshatsillo** [comment]
Через UI установить в state description min и max значения. Так же можно в двух разных тегах указать min=10 и max=25

**Comment by Ilia-SB** [comment]
Оба способа работают. Спасибо.

**Comment by Pshatsillo** [comment]
Не за что!
