### ISSUE TITLE
mode для кондиционера

### ISSUE THREAD

**Issue by Ilia-SB** [Pshatsillo/OpenhabYandexAlice#3]
Заметил, такую вещь. У меня для режима кондиционера и скорости обдува создано два item'а:
```
String Alice_AC_Mode_1 "thermostat" (gAlice_AC_1) ["mode","thermostat"]
String Alice_AC_Fan_Speed_1 "fan_speed" (gAlice_AC_1) ["mode","fan_speed"]
```
если я в приложении Яндекса меняю один из этих параметров, то **оба** item'а получают одинаковую команду. Т.е. я создал в openhab простое правило, которое выводит в консоль receivedCommand для каждого, выбираю в приложении, например, скорость вентиляции низкую и вижу в консоли:
```
Alice_AC_Mode_1 received COMMAND: low
Alice_AC_Fan_Speed_1 received COMMAND: low
```
Alice_AC_Mode_1 ведь не должен получать эту команду? Или у меня неправильно сконфигурировано?

**Comment by Pshatsillo** [comment]
Тут нужно выяснять у Яндекса, может ли быть у устройства несколько режимов.
Скорее всего, у каждого устройства может быть только один mode

пт, 14 июл. 2023 г., 03:37 Ilia-SB ***@***.***>:

**Comment by Ilia-SB** [comment]
Из описания умений термостата, есть умение mode и у него 3 разных функции: fan_speed, thermostat и heat. В принципе, поскольку набор значений у всех функций разный, я в правилах отфильтровываю, когда айтему приходят значения из чужой функции. Проблема только, когда всем 3 приходит значение auto, т.к. оно есть у всех. Пришлось у двух айтемов авто-режим убрать.

**Comment by Pshatsillo** [comment]
Исправил. Удалите и установите заново биндинг из маркета. Спасибо!
