### ISSUE TITLE
Where are settings??

### ISSUE THREAD

**Issue by FurmanenkoIgor** [Pshatsillo/OpenhabYandexAlice#4]
Helllo..

OH 4.0.4
Не вижу переход в настройку. В карточке openhabcloud есть пиктограмма, через которую я могу перейти к настройкам, но вот в карточки opehabyandexalice такого нет. 
![2023-12-02_010612](https://github.com/Pshatsillo/OpenhabYandexAlice/assets/81693923/069f2d6b-0d6c-4a04-a0fb-9ea8e7132783)

**Comment by Pshatsillo** [comment]
Добрый день. Настройки можно найти через маркет, там кнопка с шестерёнки.
Гл по какой-то причине, биндинги из маркетинга не отображают её. Для смены
настроек придётся скачать пакет отсюда и положить в папку add-ons. В 4.1
такой проблемы нет

сб, 2 дек. 2023 г., 01:15 FurmanenkoIgor ***@***.***>:

**Comment by FurmanenkoIgor** [comment]
Я тоже так подумал.
Удалил то что поставил из Магазина. Скопировал файл вручную.
В консоле бандл светиться активным, 
![2023-12-02_182659](https://github.com/Pshatsillo/OpenhabYandexAlice/assets/81693923/efd726b0-f34c-4387-a065-81ab38ca9667)
но карточки теперь вообще нет.
![2023-12-02_182700](https://github.com/Pshatsillo/OpenhabYandexAlice/assets/81693923/b249a9cb-85d3-42a4-be3b-9ef1df39895b)

**Comment by Pshatsillo** [comment]
Попробовал у себя на чистом ОХ. Биндинг появился и шестерёнка появилась
![image](https://github.com/Pshatsillo/OpenhabYandexAlice/assets/10221853/8a3f823b-d557-4b91-82b4-4174f91c213b)
![image](https://github.com/Pshatsillo/OpenhabYandexAlice/assets/10221853/d7f6d535-c65c-48ba-81f6-6363b0cd1647)
Возможно имеет смысл убедиться, что версия из маркета удалилась, перезагрузить ОХ и закинуть jar

**Comment by FurmanenkoIgor** [comment]
Бинго!!
Приложение находиться не в Bindigs-> Other Add-ons. а в Other -> Other Add-ons, хотя странно, что файлы в addons так по разному раскидываются. Спасибо за скриншот.

**Comment by Pshatsillo** [comment]
Не за что! Рад, что всё получилось!
